### ISSUE TITLE
Create blog with Jekyll

### ISSUE THREAD

**Issue by jmplaza** [TheRoboticsClub/colab-gsoc2020-Muhammad_Taha#1]
Create webpage with Jekyll minimal mistakes template. This way, we can keep track of the progress made during GSoC and share it with Google in the evaluations.

This code should be located in docs/ folder, so it is accessible as GitHub Pages.

You may use these examples (https://github.com/JdeRobot/BehaviorSuite/tree/master/docs and https://github.com/RoboticsLabURJC/2019-tfm-ignacio-arranz/tree/master/docs) and create a blog. 
The corresponding generated webpages are available at https://jderobot.github.io/BehaviorSuite/
and https://roboticslaburjc.github.io/2019-tfm-ignacio-arranz/

The idea is to create a weekly blog where you write your progress, similar to this one (https://roboticslaburjc.github.io/2019-tfm-ignacio-arranz/logbook/)

**Comment by muhammadtahasuhail** [comment]
Done.
